// Delete tables for Salesrep application

ALTER TABLE CUSTOMER DROP CONSTRAINT fk_salesrepid;
ALTER TABLE CUSTOMER DROP CONSTRAINT pk_customer;
ALTER TABLE SALESREP DROP CONSTRAINT pk_salesrep;

DROP TABLE CUSTOMER;
DROP TABLE SALESREP;
