// Delete tables for Storage Bin application

ALTER TABLE STORAGEBIN DROP CONSTRAINT fk_widgetid;
ALTER TABLE STORAGEBIN DROP CONSTRAINT pk_storagebin;
ALTER TABLE WIDGET DROP CONSTRAINT pk_widget;

DROP TABLE STORAGEBIN;
DROP TABLE WIDGET;
