// Delete tables for Enroller application

ALTER TABLE ENROLLMENT DROP CONSTRAINT fk_studentid;
ALTER TABLE ENROLLMENT DROP CONSTRAINT fk_courseid;
ALTER TABLE STUDENT DROP CONSTRAINT pk_student;
ALTER TABLE COURSE DROP CONSTRAINT pk_course;

DROP TABLE ENROLLMENT;
DROP TABLE STUDENT;
DROP TABLE COURSE;
