// Delete tables for CMPORDER application

ALTER TABLE PART DROP CONSTRAINT FK_1;
ALTER TABLE VENDOR_PART DROP CONSTRAINT FK_2;
ALTER TABLE VENDOR_PART DROP CONSTRAINT FK_3;
ALTER TABLE LINEITEM DROP CONSTRAINT FK_4;
ALTER TABLE LINEITEM DROP CONSTRAINT FK_5;




DROP TABLE LINEITEM;
DROP TABLE ORDERS;
DROP TABLE VENDOR_PART;
DROP TABLE VENDOR;
DROP TABLE PART_DETAIL;
DROP TABLE PART;
