// Delete tables for CMP roster application

ALTER TABLE TEAM DROP CONSTRAINT fk_league_id;
ALTER TABLE TEAM_PLAYER DROP CONSTRAINT fk_player_id;
ALTER TABLE TEAM_PLAYER DROP CONSTRAINT fk_team_id;
ALTER TABLE LEAGUE DROP CONSTRAINT pk_league;
ALTER TABLE PLAYER DROP CONSTRAINT pk_player;
ALTER TABLE TEAM DROP CONSTRAINT pk_team;

DROP TABLE LEAGUE;
DROP TABLE PLAYER;
DROP TABLE TEAM;
DROP TABLE TEAM_PLAYER;
